# Generated by Django 3.0.8 on 2020-07-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200725_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(default='avatar.png', upload_to='network/media/network/profilepic/'),
        ),
    ]
