# Generated by Django 3.0.8 on 2020-07-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200725_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(default='avatar.png', upload_to='profile_pic/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
